[package]
name = "java_bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
main_library = {path = "../main_library"}
jni =  "0.21.1"
jni_fn = "0.1.2"
serde_json = "1.0.105"
serde = {version = "1.0.188", features = ["derive"]}